In [2]:
# Load EDA Pckgs
import pandas as pd
import numpy as np 

In [3]:
# Load Data Viz Pkgs
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
import seaborn as sns 
import os
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
import sys
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, f1_score

import warnings

In [5]:
# ML Pkgs
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.metrics import accuracy_score, hamming_loss, classification_report


In [6]:
### Split Dataset into Train and Text
from sklearn.model_selection import train_test_split

In [12]:
# Feature engineering
from sklearn.feature_extraction.text import TfidfVectorizer



In [18]:
# Multi Label Pkgs
from skmultilearn.problem_transform import BinaryRelevance
from skmultilearn.problem_transform import ClassifierChain
from skmultilearn.problem_transform import LabelPowerset
from skmultilearn.adapt import MLkNN

In [19]:
!pip install scikit-multilearn

In [24]:
#Load the dataset into the dataframe
df = pd.read_csv(r"C:\Users\Admin8\Downloads\archive\cleaned-Data.csv")
print(df.head())



   Fever  Tiredness  Dry-Cough  Difficulty-in-Breathing  Sore-Throat  \
0      1          1          1                        1            1   
1      1          1          1                        1            1   
2      1          1          1                        1            1   
3      1          1          1                        1            1   
4      1          1          1                        1            1   

   None_Sympton  Pains  Nasal-Congestion  Runny-Nose  Diarrhea  ...  \
0             0      1                 1           1         1  ...   
1             0      1                 1           1         1  ...   
2             0      1                 1           1         1  ...   
3             0      1                 1           1         1  ...   
4             0      1                 1           1         1  ...   

   Gender_Male  Gender_Transgender  Severity_Mild  Severity_Moderate  \
0            1                   0              1                  0

In [16]:
# Assuming df is the DataFrame containing the data
print(df.columns)  # Verify column names with 'df.columns'






Index(['Fever', 'Tiredness', 'Dry-Cough', 'Difficulty-in-Breathing',
       'Sore-Throat', 'None_Sympton', 'Pains', 'Nasal-Congestion',
       'Runny-Nose', 'Diarrhea', 'None_Experiencing', 'Age_0-9', 'Age_10-19',
       'Age_20-24', 'Age_25-59', 'Age_60+', 'Gender_Female', 'Gender_Male',
       'Gender_Transgender', 'Severity_Mild', 'Severity_Moderate',
       'Severity_None', 'Severity_Severe', 'Contact_Dont-Know', 'Contact_No',
       'Contact_Yes', 'Country'],
      dtype='object')


In [17]:
#Count'Fever'column 
sizes = df['Fever'].value_counts(sort=True)
print(sizes)

0    217800
1     99000
Name: Fever, dtype: int64


In [31]:
#Drop the columns that do not have effect on the model
df.drop(['Age_0-9'], axis = 1, inplace = True)
df.drop(['Age_10-19'], axis = 1, inplace = True)
df.drop(['Age_20-24'], axis = 1, inplace = True)
df.drop(['Age_25-59'], axis = 1, inplace = True)
df.drop(['Age_60+'], axis = 1, inplace = True)
df.drop(['Gender_Female'], axis = 1, inplace = True)
df.drop(['Gender_Male'], axis = 1, inplace = True)
df.drop(['Gender_Transgender'], axis = 1, inplace = True)
df.drop(['None_Experiencing'], axis = 1, inplace = True)
df.drop(['None_Sympton'], axis = 1, inplace = True)
df.drop(['Contact_Dont-Know'], axis = 1, inplace = True)
df.drop(['Contact_No'], axis = 1, inplace = True)
df.drop(['Contact_Yes'], axis = 1, inplace = True)
df.drop(['Country'], axis = 1, inplace = True)



print(df.head())

   Fever  Tiredness  Dry-Cough  Difficulty-in-Breathing  Sore-Throat  Pains  \
0      1          1          1                        1            1      1   
1      1          1          1                        1            1      1   
2      1          1          1                        1            1      1   
3      1          1          1                        1            1      1   
4      1          1          1                        1            1      1   

   Nasal-Congestion  Runny-Nose  Diarrhea  Severity_Mild  Severity_Moderate  \
0                 1           1         1              1                  0   
1                 1           1         1              1                  0   
2                 1           1         1              1                  0   
3                 1           1         1              0                  1   
4                 1           1         1              0                  1   

   Severity_None  Severity_Severe  
0             

In [32]:
# Check the data type
df.dtypes


Fever                      int64
Tiredness                  int64
Dry-Cough                  int64
Difficulty-in-Breathing    int64
Sore-Throat                int64
Pains                      int64
Nasal-Congestion           int64
Runny-Nose                 int64
Diarrhea                   int64
Severity_Mild              int64
Severity_Moderate          int64
Severity_None              int64
Severity_Severe            int64
dtype: object

In [33]:
# Convert to Float
df = df.astype(float)
df.dtypes

Fever                      float64
Tiredness                  float64
Dry-Cough                  float64
Difficulty-in-Breathing    float64
Sore-Throat                float64
Pains                      float64
Nasal-Congestion           float64
Runny-Nose                 float64
Diarrhea                   float64
Severity_Mild              float64
Severity_Moderate          float64
Severity_None              float64
Severity_Severe            float64
dtype: object

# Train the model using SVM classifier

In [35]:

import pandas as pd
from sklearn.model_selection import train_test_split

# Assuming the column name for the target variable is 'severity' which will contain 4 separate severity classes

# Define the input features (X)

X = df[['Fever', 'Tiredness', 'Dry-Cough', 'Difficulty-in-Breathing','Sore-Throat', 'Pains', 'Nasal-Congestion', 'Runny-Nose', 'Diarrhea']]

# Define the target variables (y)
y = df[['Severity_Mild', 'Severity_Moderate', 'Severity_None', 'Severity_Severe']]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)



In [65]:
# Split Data 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [132]:
print(X_train)

        Fever  Tiredness  Dry-Cough  Difficulty-in-Breathing  Sore-Throat  \
125151      1          0          0                        0            0   
36050       1          1          1                        1            0   
222457      0          1          1                        1            1   
250914      0          0          0                        1            1   
296710      0          1          1                        0            0   
...       ...        ...        ...                      ...          ...   
119879      0          0          0                        1            1   
259178      0          0          1                        0            0   
131932      0          1          1                        0            0   
146867      0          1          0                        0            0   
121958      0          0          1                        0            0   

        Pains  Nasal-Congestion  Runny-Nose  Diarrhea  
125151      1      

In [136]:
print(y_train)

[[1 0 0 0]
 [1 0 0 0]
 [0 0 1 0]
 ...
 [0 0 1 0]
 [1 0 0 0]
 [0 1 0 0]]


# Support Vector Machine Classifier

In [92]:
# Create and fit the SVM model

model = SVC()
model.fit(X_train, y_train)

# Evaluate the model
accuracy = model.score(X_test, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.7519097222222222


svm_classifier = SVC(kernel='rbf', C=1.0, gamma='scale')
svm_classifier.fit(X_train, y_train)
y_pred = svm_classifier.predict(X_test)

#Evaluate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)