In [1]:
# Load EDA Pckgs
import pandas as pd
import numpy as np 

In [2]:
# Load Data Viz Pkgs
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
import seaborn as sns 
import os
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
import sys
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, f1_score

import warnings

In [4]:
# ML Pkgs
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.metrics import accuracy_score, hamming_loss, classification_report


In [5]:
### Split Dataset into Train and Text
from sklearn.model_selection import train_test_split

In [2]:
#Load the dataset into the dataframe
df = pd.read_csv(r"C:\Users\Admin8\Downloads\archive\cleaned-Data.csv")
print(df.head())



   Fever  Tiredness  Dry-Cough  Difficulty-in-Breathing  Sore-Throat  \
0      1          1          1                        1            1   
1      1          1          1                        1            1   
2      1          1          1                        1            1   
3      1          1          1                        1            1   
4      1          1          1                        1            1   

   None_Sympton  Pains  Nasal-Congestion  Runny-Nose  Diarrhea  ...  \
0             0      1                 1           1         1  ...   
1             0      1                 1           1         1  ...   
2             0      1                 1           1         1  ...   
3             0      1                 1           1         1  ...   
4             0      1                 1           1         1  ...   

   Gender_Male  Gender_Transgender  Severity_Mild  Severity_Moderate  \
0            1                   0              1                  0

In [14]:
# Assuming df is the DataFrame containing the data
print(df.columns)  # Verify column names with 'df.columns'






Index(['Fever', 'Tiredness', 'Dry-Cough', 'Difficulty-in-Breathing',
       'Sore-Throat', 'None_Sympton', 'Pains', 'Nasal-Congestion',
       'Runny-Nose', 'Diarrhea', 'None_Experiencing', 'Age_0-9', 'Age_10-19',
       'Age_20-24', 'Age_25-59', 'Age_60+', 'Gender_Female', 'Gender_Male',
       'Gender_Transgender', 'Severity_Mild', 'Severity_Moderate',
       'Severity_None', 'Severity_Severe', 'Contact_Dont-Know', 'Contact_No',
       'Contact_Yes', 'Country'],
      dtype='object')


In [19]:
# Convert to Float
df = df.astype(float)
df.dtypes

Fever                      float64
Tiredness                  float64
Dry-Cough                  float64
Difficulty-in-Breathing    float64
Sore-Throat                float64
Pains                      float64
Nasal-Congestion           float64
Runny-Nose                 float64
Diarrhea                   float64
Severity_Mild              float64
Severity_Moderate          float64
Severity_None              float64
Severity_Severe            float64
dtype: object

In [ ]:
df.drop(['Age_0-9'], axis = 1, inplace = True)
df.drop(['Age_10-19'], axis = 1, inplace = True)
df.drop(['Age_20-24'], axis = 1, inplace = True)
df.drop(['Age_25-59'], axis = 1, inplace = True)
df.drop(['Age_60+'], axis = 1, inplace = True)
df.drop(['Gender_Female'], axis = 1, inplace = True)
df.drop(['Gender_Male'], axis = 1, inplace = True)
df.drop(['Gender_Transgender'], axis = 1, inplace = True)
df.drop(['None_Experiencing'], axis = 1, inplace = True)
df.drop(['None_Sympton'], axis = 1, inplace = True)
df.drop(['Contact_Dont-Know'], axis = 1, inplace = True)
df.drop(['Contact_No'], axis = 1, inplace = True)
df.drop(['Contact_Yes'], axis = 1, inplace = True)

In [4]:
#Drop the columns that do not have effect on the model

df.drop(['Country'], axis = 1, inplace = True)


print(df.head())

   Fever  Tiredness  Dry-Cough  Difficulty-in-Breathing  Sore-Throat  Pains  \
0      1          1          1                        1            1      1   
1      1          1          1                        1            1      1   
2      1          1          1                        1            1      1   
3      1          1          1                        1            1      1   
4      1          1          1                        1            1      1   

   Nasal-Congestion  Runny-Nose  Diarrhea  Severity_Mild  Severity_Moderate  \
0                 1           1         1              1                  0   
1                 1           1         1              1                  0   
2                 1           1         1              1                  0   
3                 1           1         1              0                  1   
4                 1           1         1              0                  1   

   Severity_None  Severity_Severe  
0             

# Improve the class imbalnce using SMOTE technique

In [5]:

import pandas as pd
from sklearn.model_selection import train_test_split

# Assuming the column name for the target variable is 'severity' which will contain 4 separate severity classes

# Define the input features (X)

X = df[['Fever', 'Tiredness', 'Dry-Cough', 'Difficulty-in-Breathing','Sore-Throat', 'Pains', 'Nasal-Congestion', 'Runny-Nose', 'Diarrhea']]

# Define the target variables (y)
y = df[['Severity_Mild', 'Severity_Moderate', 'Severity_None', 'Severity_Severe']]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)



In [12]:
from sklearn.ensemble import RandomForestClassifier


# Using each class to create 4 instances of prediction



In [6]:
# y1 = Severity_None
from sklearn.model_selection import train_test_split

X = df.drop(['Severity_Mild', 'Severity_Moderate', 'Severity_None', 'Severity_Severe'], axis=1)  # Input features (all columns except the target variable)
y1 = df[['Severity_None']].values  # Target variable as a NumPy array

# Split the data into training and testing sets
X_train, X_test, y1_train, y1_test = train_test_split(X, y1, test_size=0.2, random_state=42)

In [7]:
print(df['Severity_None'])

0         0
1         0
2         0
3         0
4         0
         ..
316795    0
316796    0
316797    1
316798    1
316799    1
Name: Severity_None, Length: 316800, dtype: int64


In [8]:
# y2 = Severity_Mild
from sklearn.model_selection import train_test_split

X = df.drop(['Severity_Mild', 'Severity_Moderate', 'Severity_None', 'Severity_Severe'], axis=1)  # Input features (all columns except the target variable)
y2 = df[['Severity_Mild']].values  # Target variable as a NumPy array

# Split the data into training and testing sets
X_train, X_test, y2_train, y2_test = train_test_split(X, y2, test_size=0.2, random_state=42)

In [9]:
# y3 = Severity_Moderate
from sklearn.model_selection import train_test_split

X = df.drop(['Severity_Mild', 'Severity_Moderate', 'Severity_None', 'Severity_Severe'], axis=1)  # Input features (all columns except the target variable)
y3 = df[['Severity_Moderate']].values  # Target variable as a NumPy array

# Split the data into training and testing sets
X_train, X_test, y3_train, y3_test = train_test_split(X, y3, test_size=0.2, random_state=42)

In [10]:
# y4 = Severity_Severe
from sklearn.model_selection import train_test_split

X = df.drop(['Severity_Mild', 'Severity_Moderate', 'Severity_None', 'Severity_Severe'], axis=1)  # Input features (all columns except the target variable)
y4 = df[['Severity_Severe']].values  # Target variable as a NumPy array

# Split the data into training and testing sets
X_train, X_test, y4_train, y4_test = train_test_split(X, y4, test_size=0.2, random_state=42)

In [13]:
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler

# Apply SMOTE oversampling for y1
smote_y1 = SMOTE()
X_train_smote_y1, y1_train_smote = smote_y1.fit_resample(X_train, y1_train)

# Apply RandomUnderSampler undersampling for y2
rus_y2 = RandomUnderSampler()
X_train_rus_y2, y2_train_rus = rus_y2.fit_resample(X_train, y2_train)

# Apply SMOTE oversampling for y3
smote_y3 = SMOTE()
X_train_smote_y3, y3_train_smote = smote_y3.fit_resample(X_train, y3_train)

# Apply RandomUnderSampler undersampling for y4
rus_y4 = RandomUnderSampler()
X_train_rus_y4, y4_train_rus = rus_y4.fit_resample(X_train, y4_train)

# Now you can use the balanced data for training and testing
# Example with oversampled data for y1
classifier_y1 = RandomForestClassifier()  # Replace YourClassifier with your desired classifier
classifier_y1.fit(X_train_smote_y1, y1_train_smote)
y1_pred = classifier_y1.predict(X_test)

# Example with undersampled data for y2
classifier_y2 = RandomForestClassifier()  # Replace YourClassifier with your desired classifier
classifier_y2.fit(X_train_rus_y2, y2_train_rus)
y2_pred = classifier_y2.predict(X_test)

# Example with oversampled data for y3
classifier_y3 = RandomForestClassifier()  # Replace YourClassifier with your desired classifier
classifier_y3.fit(X_train_smote_y3, y3_train_smote)
y3_pred = classifier_y3.predict(X_test)

# Example with undersampled data for y4
classifier_y4 = RandomForestClassifier()  # Replace YourClassifier with your desired classifier
classifier_y4.fit(X_train_rus_y4, y4_train_rus)
y4_pred = classifier_y4.predict(X_test)


In [14]:
# Calculate accuracy
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Calculate metric scores for y1
y1_accuracy = accuracy_score(y1_test, y1_pred)
y1_precision = precision_score(y1_test, y1_pred)
y1_recall = recall_score(y1_test, y1_pred)
y1_f1 = f1_score(y1_test, y1_pred)


# Calculate metric scores for y2
y2_accuracy = accuracy_score(y2_test, y2_pred)
y2_precision = precision_score(y2_test, y2_pred)
y2_recall = recall_score(y2_test, y2_pred)
y2_f1 = f1_score(y2_test, y2_pred)

# Calculate metric scores for y3
y3_accuracy = accuracy_score(y3_test, y3_pred)
y3_precision = precision_score(y3_test, y3_pred)
y3_recall = recall_score(y3_test, y3_pred)
y3_f1 = f1_score(y3_test, y3_pred)

# Calculate metric scores for y4
y4_accuracy = accuracy_score(y4_test, y4_pred)
y4_precision = precision_score(y4_test, y4_pred)
y4_recall = recall_score(y4_test, y4_pred)
y4_f1 = f1_score(y4_test, y4_pred)

# Print the metric scores
print("Metrics scores for y1:")
print("Accuracy:", y1_accuracy)
print("Precision:", y1_precision)
print("Recall:", y1_recall)
print("F1-score:", y1_f1)
print()

print("Metrics scores for y2:")
print("Accuracy:", y2_accuracy)
print("Precision:", y2_precision)
print("Recall:", y2_recall)
print("F1-score:", y2_f1)
print()

print("Metrics scores for y3:")
print("Accuracy:", y3_accuracy)
print("Precision:", y3_precision)
print("Recall:", y3_recall)
print("F1-score:", y3_f1)
print()

print("Metrics scores for y4:")
print("Accuracy:", y4_accuracy)
print("Precision:", y4_precision)
print("Recall:", y4_recall)
print("F1-score:", y4_f1)


Metrics scores for y1:
Accuracy: 0.4696811868686869
Precision: 0.23679863118768069
Recall: 0.5094243828139874
F1-score: 0.32331084482932226

Metrics scores for y2:
Accuracy: 0.4845959595959596
Precision: 0.24446214651184167
Recall: 0.4994679186228482
F1-score: 0.32825934915867855

Metrics scores for y3:
Accuracy: 0.49761679292929295
Precision: 0.2397685669456067
Recall: 0.46105977748444277
F1-score: 0.31547708651426853

Metrics scores for y4:
Accuracy: 0.493102904040404
Precision: 0.24268767260858648
Recall: 0.4919524142757173
F1-score: 0.3250320492612908


# Using Multi-Perceptron to replace the random classifier

In [16]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Create an instance of the MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(20, 15, 100), activation='relu', random_state=42)

# Fit the MLP classifier to the training data
mlp.fit(X_train, y_train)

# Make predictions on the test data
y_pred = mlp.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='micro')
recall = recall_score(y_test, y_pred, average='micro')
f1 = f1_score(y_test, y_pred, average='micro')

# Print the metrics scores
print("Metrics scores:")
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

Metrics scores:
Accuracy: 0.0
Precision: 0.0
Recall: 0.0
F1-score: 0.0


C:\Users\admin\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [135]:
from sklearn.model_selection import train_test_split

X = df.drop(['Severity_Mild', 'Severity_Moderate', 'Severity_None', 'Severity_Severe'], axis=1)  # Input features (all columns except the target variable)
y = df[['Severity_Mild', 'Severity_Moderate', 'Severity_None', 'Severity_Severe']].values  # Target variable as a NumPy array

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)


In [132]:
print(X_train)

        Fever  Tiredness  Dry-Cough  Difficulty-in-Breathing  Sore-Throat  \
125151      1          0          0                        0            0   
36050       1          1          1                        1            0   
222457      0          1          1                        1            1   
250914      0          0          0                        1            1   
296710      0          1          1                        0            0   
...       ...        ...        ...                      ...          ...   
119879      0          0          0                        1            1   
259178      0          0          1                        0            0   
131932      0          1          1                        0            0   
146867      0          1          0                        0            0   
121958      0          0          1                        0            0   

        Pains  Nasal-Congestion  Runny-Nose  Diarrhea  
125151      1      

In [136]:
print(y_train)

[[1 0 0 0]
 [1 0 0 0]
 [0 0 1 0]
 ...
 [0 0 1 0]
 [1 0 0 0]
 [0 1 0 0]]


In [137]:
model = RandomForestClassifier(n_estimators = 10, random_state = 30)
model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=10, random_state=30)

In [134]:
prediction_test = model.predict(X_test)
#print(y_test, prediction_test)

from sklearn import metrics
#Print the prediction accuracy
print ("Accuracy = ", metrics.accuracy_score(y_test, prediction_test))
#Test accuracy for various test sizes and see how it gets better with more training data

#One amazing feature of Random forest is that it provides us info on feature importances
# Get numerical feature importances
#importances = list(model.feature_importances_)

#Let us print them into a nice format.

feature_list = list(X.columns)
feature_imp = pd.Series(model.feature_importances_,index=feature_list).sort_values(ascending=False)
print(feature_imp)

Accuracy =  0.0
Dry-Cough                  0.153289
Pains                      0.128750
Nasal-Congestion           0.122165
Runny-Nose                 0.114081
Fever                      0.113166
Tiredness                  0.108462
Difficulty-in-Breathing    0.099367
Sore-Throat                0.084423
Diarrhea                   0.076297
dtype: float64


# Improving the accuracy of the Model using XGBoost and Cross Validation

In [88]:
pip install xgboost

Note: you may need to restart the kernel to use updated packages.


In [89]:
import xgboost as xgb
from sklearn.metrics import accuracy_score

# Assuming you have already split your data into X_train, X_test, y_train, y_test

# Create an XGBoost classifier
model = xgb.XGBClassifier()

# Train the model on the training data
model.fit(X_train, y_train)

# Make predictions on the test data
predictions = model.predict(X_test)

# Calculate accuracy score
accuracy = accuracy_score(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))


Accuracy: 75.19%


In [90]:
#Cross-Validation
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

# Assuming you have already split your data into X_train, X_test, y_train, y_test

# Create a Random Forest Classifier
model = RandomForestClassifier()

# Perform cross-validation
cv_scores = cross_val_score(model, X_train, y_train, cv=5)

# Print the cross-validation scores
print("Cross-Validation Scores:", cv_scores)
print("Mean Accuracy:", cv_scores.mean())


Cross-Validation Scores: [0.74952652 0.74952652 0.74952652 0.74952652 0.74950679]
Mean Accuracy: 0.7495225694444445


In [91]:
# Create a random forest classifier
model = RandomForestClassifier()

# Train the model
model.fit(X, y)

# Get feature importances
importances = model.feature_importances_

# Create a pandas Series for feature importances
feature_imp = pd.Series(importances, index=X.columns).sort_values(ascending=False)

# Print feature importances
print(feature_imp)






Diarrhea                   0.125546
Runny-Nose                 0.123422
Nasal-Congestion           0.119573
Pains                      0.110879
Difficulty-in-Breathing    0.106977
Dry-Cough                  0.106296
Fever                      0.106088
Sore-Throat                0.102702
Tiredness                  0.098517
dtype: float64


# Support Vector Machine Classifier

In [92]:
# Create and fit the SVM model

model = SVC()
model.fit(X_train, y_train)

# Evaluate the model
accuracy = model.score(X_test, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.7519097222222222


svm_classifier = SVC(kernel='rbf', C=1.0, gamma='scale')
svm_classifier.fit(X_train, y_train)
y_pred = svm_classifier.predict(X_test)

#Evaluate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

In [ ]:
from sklearn.svm import SVC
svm = SVC(kernel="linear",random_state =0)  
svm.fit(x_train, y_train)
y_pred = svm.predict(x_test) 

# Best parameters ior the model

In [ ]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the parameter grid for grid search
param_grid = {
    'kernel': ['linear', 'poly', 'rbf', 'sigmoid'],
    'C': [0.1, 1, 10],
    'gamma': [0.1, 0.01, 0.001]
}

# Create the SVM classifier
svm_classifier = SVC()

# Create the GridSearchCV object for hyperparameter tuning
grid_search = GridSearchCV(svm_classifier, param_grid, scoring='accuracy', cv=5)

# Fit the model on the training data
grid_search.fit(X_train, y_train)

# Get the best hyperparameters
best_params = grid_search.best_params_
print("Best Hyperparameters:", best_params)

# Create a new SVM classifier with the best hyperparameters
best_svm_classifier = SVC(kernel=best_params['kernel'], C=best_params['C'], gamma=best_params['gamma'])

# Train the model with the best hyperparameters
best_svm_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_svm_classifier.predict(X_test)

# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("F1 Score:", f1)